<a href="https://colab.research.google.com/github/SanjayBukka/Customer-Churn-Prediction-Bank-/blob/main/Customer_Churn_Prediction(BankCustomers).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import kagglehub
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
file_path = "Churn_Modelling.csv"
data = pd.read_csv(file_path)

In [4]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
data['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

We Can see the imbalance in the dataset so to balance this will go with oversampling Techniqu i.e SMOTE

DATA CLEANING

In [8]:
# Droping Irrelevant Columns
data_cleaned=data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data=data_cleaned

In [9]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
label_encoder = LabelEncoder()
data_cleaned["Gender"] = label_encoder.fit_transform(data_cleaned["Gender"])

data_cleaned = pd.get_dummies(data_cleaned, columns=["Geography"], drop_first=True)

In [11]:
data_cleaned.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,False,False
1,608,0,41,1,83807.86,1,0,1,112542.58,0,False,True
2,502,0,42,8,159660.80,3,1,0,113931.57,1,False,False
3,699,0,39,1,0.00,2,0,0,93826.63,0,False,False
4,850,0,43,2,125510.82,1,1,1,79084.10,0,False,True

In [12]:
# Scale numerical features
scaler = StandardScaler()
numerical_features = ["CreditScore", "Age", "Balance", "EstimatedSalary"]
data_cleaned[numerical_features] = scaler.fit_transform(data_cleaned[numerical_features])

In [13]:
data_cleaned.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,-0.326221,0,0.293517,2,-1.225848,1,1,1,0.021886,1,False,False
1,-0.440036,0,0.198164,1,0.117350,1,0,1,0.216534,0,False,True
2,-1.536794,0,0.293517,8,1.333053,3,1,0,0.240687,1,False,False
3,0.501521,0,0.007457,1,-1.225848,2,0,0,-0.108918,0,False,False
4,2.063884,0,0.388871,2,0.785728,1,1,1,-0.365276,0,False,True

In [14]:
# Spilt dataset into features X and y
X=data_cleaned.drop("Exited",axis=1)
y=data_cleaned["Exited"]

In [16]:
#Split train and Test data(80-20 rule)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42, stratify=y)

print(f"Training set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")

Training set size: (8000, 11)
Test set size: (2000, 11)

Adjusting Class Imbalance

In [17]:
from imblearn.over_sampling import SMOTE
from collections import Counter

In [18]:
#apply SMOTE on training data
smote=SMOTE(random_state=42)
X_train_balanced, y_train_balanced= smote.fit_resample(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(

In [19]:
#check class distribution
print(Counter(y_train))
print(Counter(y_train_balanced))

Counter({0: 6370, 1: 1630})
Counter({1: 6370, 0: 6370})

Building model using Logistic regression

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
log_reg=LogisticRegression(random_state=42)
log_reg.fit(X_train_balanced, y_train_balanced)
y_pred_lr=log_reg.predict(X_test)

In [22]:
#results by logistic regression
print("Logistic Regression Results")
print(classification_report(y_test, y_pred_lr))
print("confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))

Logistic Regression Results
              precision    recall  f1-score   support

           0       0.89      0.75      0.81      1593
           1       0.39      0.64      0.49       407

    accuracy                           0.73      2000
   macro avg       0.64      0.69      0.65      2000
weighted avg       0.79      0.73      0.75      2000

confusion Matrix:
 [[1195  398]
 [ 148  259]]

Building model using Decision Trees

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
decision_tree= DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train_balanced, y_train_balanced)
y_pred_dt=decision_tree.predict(X_test)

In [26]:
#results by Decision Tree

print("\nDecision Tree Performance")
print(classification_report(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))

Decision Tree Performance
              precision    recall  f1-score   support

           0       0.88      0.78      0.83      1593
           1       0.41      0.59      0.48       407

    accuracy                           0.74      2000
   macro avg       0.64      0.68      0.66      2000
weighted avg       0.78      0.74      0.76      2000

Confusion Matrix:
 [[1246  347]
 [ 168  239]]